version: "3"

# Local development testing environment.
services:
  test-db:
    image: postgres:12
    ports:
      - "8081:5432"
    container_name: test-db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=ktor_template

  smartspanner-app:
    build:
      context: ./
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - JDBC_URL=jdbc:postgresql://test-db:5432/ktor_template
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - KTOR_ENV=dev
      - KTOR_PORT=8080
      - JAVA_OPTS=-server -Xms256m -Xmx512m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -XX:NativeMemoryTracking=summary -Xrunjdwp:server=y,transport=dt_socket,address=5005,suspend=n
    links:
      - test-db
    container_name: ktor-template-app

