name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.1.1
    - name: Commit updated changelog
      uses: test-room-7/action-update-file@v1
      with:
        file-path: |
          /github/workspace/CHANGELOG.md
        commit-msg: Updated the changelog