name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  publish-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.MAVEN_SIGNING_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
          gpg --export-secret-keys ${{secrets.MAVEN_SIGNING_KEY_ID}} > /tmp/waterdog-oss.asc
      - name: Publish artifact
        run: >-
          ./gradlew publish -Psigning.keyId=${{secrets.MAVEN_SIGNING_KEY_ID}}
          -Psigning.password=${{secrets.MAVEN_SIGNING_KEY_PASSWORD}}
          -Psigning.secretKeyRingFile=/tmp/waterdog-oss.asc
          -PossrhUsername=${{secrets.OSSRH_USERNAME}}
          -PossrhPassword=${{secrets.OSSRH_PASSWORD}}
 
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Read changelog
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CHANGELOG.md
      - name: Create GitHub release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: ${{ steps.changelog.outputs.content }}
          draft: false
